server:
  port: 8082

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=microservices;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: Hotel-Service
  config:
    import: optional:configserver:http://localhost:8085
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true


